name: scootly_customer
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  pinput: ^5.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  internet_connection_checker_plus: ^2.5.2
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0

  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/
